spring:
    config:
        import: 
    application:
        name: TicketSystem
    datasource:

        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: update
server:
    port: 5000
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,loggers,env