spring:
    config:
        import: env.yaml
    application:
        name: TicketSystem
    datasource:
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: update
server:
    port: 5000
logging:
  level:
    root: DEBUG  # Set the root logger level
  file:
    name: logs/TicketSystem.log  # Set the name of the log file
    max-size: 10MB  # Set the maximum file size
    max-history: 7  # Keep 7 archived log files
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,loggers,env